version: "3.8"
services:
  proxy:
    image: nginx:1.19-alpine
    networks:
      - networks_thanvasu_dev
    container_name: nginx-thavasu-dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/thanvasu-dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: always

  frontend-thachang:
    image: thanvasu/web-thachang:v0.0.10.dev
    networks:
      - networks_thanvasu_dev
    container_name: web-thachang-dev
    ports:
      - 3000:3000

  frontend-thachang-admin:
    image: thanvasu/web-thachang-admin:v0.0.13.dev
    networks:
      - networks_thanvasu_dev
    container_name: web-thachang-admin-dev
    ports:
      - 3001:3000

  backend-thachang:
    image: thanvasu/api-thachang:v0.0.6.dev
    networks:
      - networks_thanvasu_dev
    container_name: api-thachang-dev
    ports:
      - 8081:8081

networks:
  networks_thanvasu_dev:
